In [ ]:
import pandas as pd

In [ ]:
data = pd.read_excel('main_data_with_indics_nifty50daily_weekly_monthly_vix_daily_weekly_monthly_FITERED_CLEANED_industry_news_v5.xlsx')
data

,mapping_key,url,Issuer Company,Open Date,Close Date,Listing Date,Issue Price (Rs),Issue Size (Rs Cr.),Lot Size,Exchange,...,Chg%_vix_monthly,month,year,Company Name,Sector,Industry,news_url,news_headine,news_synopsis,news_content
0,0,https://www.chittorgarh.com/ipo/infibeam_ipo/532/,Infibeam Incorporation Ltd IPO,"Mar 21, 2016","Mar 23, 2016","Apr 04, 2016",432,450.00,34,"BSE, NSE",...,16.92%,2,2016,INFIBEAM AVENUES LIMITED,Commercial Services,Miscellaneous Commercial Services,['https://economictimes.indiatimes.com/markets...,['Pricing of Infibeam IPO appears too ambitiou...,"['Unlike several other ecommerce startups, whi...","['Unlike several other ecommerce startups, whi..."
1,1,https://www.chittorgarh.com/ipo/route-mobile-i...,Route Mobile Ltd IPO,"Sep 09, 2020","Sep 11, 2020","Sep 21, 2020",350,600.00,40,"BSE, NSE",...,-5.61%,8,2020,route mobile ltd,Communications,Major Telecommunications,['https://economictimes.indiatimes.com/tech/in...,['Route Mobile acquires competitor Cellent Tec...,['The company is also in advanced talks with a...,"['MUMBAI: Route Mobile , a messaging and voice..."
2,2,https://www.chittorgarh.com/ipo/valiant-labora...,Valiant Laboratories Limited IPO,"Sep 27, 2023","Oct 03, 2023","Oct 06, 2023",140,152.46,105,"BSE, NSE",...,-5.06%,9,2023,valiant laboratories limited,Health Technology,Pharmaceuticals: Major,['https://economictimes.indiatimes.com/markets...,"['Valiant Laboratories files IPO papers', 'Val...","['Valiant Laboratories Ltd, the subsidiary of ...","['Valiant Laboratories Ltd, the subsidiary of ..."
3,3,https://www.chittorgarh.com/ipo/irm-energy-ipo...,IRM Energy Limited IPO,"Oct 18, 2023","Oct 20, 2023","Oct 26, 2023",505,545.40,29,"BSE, NSE",...,-5.06%,9,2023,irm energy limited,Energy Minerals,Integrated Oil,NaN,NaN,NaN,NaN
4,4,https://www.chittorgarh.com/ipo/bse-limited-ip...,BSE Limited IPO,"Jan 23, 2017","Jan 25, 2017","Feb 03, 2017",806,1243.43,18,NSE,...,-8.22%,12,2016,BSE LTD,Finance,Investment Banks/Brokers,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,689,https://www.chittorgarh.com/ipo/heranba-indust...,Heranba Industries Limited IPO,"Feb 23, 2021","Feb 25, 2021","Mar 05, 2021",627,625.24,23,"BSE, NSE",...,20.14%,1,2021,heranba industries limited,Process Industries,Chemicals: Agricultural,NaN,NaN,NaN,NaN
414,691,https://www.chittorgarh.com/ipo/rites-limited-...,RITES Limited IPO,"Jun 20, 2018","Jun 22, 2018","Jul 02, 2018",185,460.51,80,"BSE, NSE",...,6.96%,5,2018,rites limited,Commercial Services,Miscellaneous Commercial Services,NaN,NaN,NaN,NaN
415,692,https://www.chittorgarh.com/ipo/indian-energy-...,Indian Energy Exchange Ltd IPO,"Oct 09, 2017","Oct 11, 2017","Oct 23, 2017",1650,1000.73,9,"BSE, NSE",...,4.46%,9,2017,indian energy exchange limited,Finance,Investment Banks/Brokers,NaN,NaN,NaN,NaN
416,693,https://www.chittorgarh.com/ipo/muthoot_ipo/300/,Muthoot Finance Ltd IPO,"Apr 18, 2011","Apr 21, 2011","May 06, 2011",175,901.25,40,"BSE, NSE",...,-9.10%,3,2011,muthoot finance ltd,Finance,Finance/Rental/Leasing,['https://economictimes.indiatimes.com/markets...,['Muthoot Finance IPO valuations reasonable: P...,"[""Prabhudas Lilladher is of the view that init...",['MUMBAI: Prabhudas Lilladher is of the view t...
417,697,https://www.chittorgarh.com/ipo/c_mahendra_ipo...,C Mahendra Exports Ltd IPO,"Dec 31, 2010","Jan 06, 2011","Jan 20, 2011",110,165.00,60,"BSE, NSE",...,-20.04%,12,2010,C Mahendra Exports,Non-Energy Minerals,Precious Metals,NaN,NaN,NaN,NaN

# Add performance of recent IPOs

In [ ]:
# Remove rupee sign

# Define Success_Open, Success_Close, Success_High by comparing with Issue price

# Last quater IPO success rate calculate and add to original data


# Prepare data
# Year, Quarter, Industry (Board), Success_Open, Success_Close, Success_High
# Remove Industry & roll up

In [ ]:
data['Close Date'] = pd.to_datetime(data['Close Date'])
data_sort = data.sort_values('Close Date')
data_sort

,mapping_key,url,Issuer Company,Open Date,Close Date,Listing Date,Issue Price (Rs),Issue Size (Rs Cr.),Lot Size,Exchange,...,Chg%_vix_monthly,month,year,Company Name,Sector,Industry,news_url,news_headine,news_synopsis,news_content
263,433,https://www.chittorgarh.com/ipo/edserv_softsys...,Edserv Softsystems Limited IPO,"Feb 05, 2009",2009-02-09,"Mar 02, 2009",60,23.84,100,"BSE, NSE",...,-2.30%,1,2009,edserv soft systems ltd.,Technology Services,Packaged Software,NaN,NaN,NaN,NaN
362,607,https://www.chittorgarh.com/ipo/mahindra_holid...,Mahindra Holidays and Resorts India Ltd IPO,"Jun 23, 2009",2009-06-26,"Jul 16, 2009",300,277.96,20,"BSE, NSE",...,-13.57%,5,2009,mahindra holidays & resorts in,Consumer Services,Other Consumer Services,NaN,NaN,NaN,NaN
306,504,https://www.chittorgarh.com/ipo/excel_infoways...,Excel Infoways Limited IPO,"Jul 14, 2009",2009-07-17,"Aug 3, 2009",85,48.17,80,"BSE, NSE",...,5.56%,6,2009,excel infoway limited,Technology Services,Information Technology Services,NaN,NaN,NaN,NaN
11,15,https://www.chittorgarh.com/ipo/raj_oil_mills_...,Raj Oil Mills Limited IPO,"Jul 20, 2009",2009-07-23,"Aug 12, 2009",120,114.00,50,"BSE, NSE",...,5.56%,6,2009,raj oil mills ltd,Process Industries,Agricultural Commodities/Milling,NaN,NaN,NaN,NaN
222,369,https://www.chittorgarh.com/ipo/adani_power_ip...,Adani Power Limited IPO,"Jul 28, 2009",2009-07-31,"Aug 20, 2009",100,3016.52,65,"BSE, NSE",...,-7.83%,7,2009,adani power ltd,Utilities,Electric Utilities,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,166,https://www.chittorgarh.com/ipo/happy-forgings...,Happy Forgings Limited IPO,"Dec 19, 2023",2023-12-21,"Dec 27, 2023",850,1008.59,17,"BSE, NSE",...,7.32%,11,2023,happy forgings limited,Producer Manufacturing,Metal Fabrication,NaN,NaN,NaN,NaN
130,214,https://www.chittorgarh.com/ipo/mufti-ipo/1595/,Credo Brands Marketing Limited IPO,"Dec 19, 2023",2023-12-21,"Dec 27, 2023",280,549.78,53,"BSE, NSE",...,7.32%,11,2023,credo brands marketing limited,Retail Trade,Apparel/Footwear Retail,NaN,NaN,NaN,NaN
343,568,https://www.chittorgarh.com/ipo/rbz-jewellers-...,RBZ Jewellers Limited IPO,"Dec 19, 2023",2023-12-21,"Dec 27, 2023",100,100.00,150,"BSE, NSE",...,7.32%,11,2023,rbz jewellers limited,Consumer Durables,Other Consumer Specialties,['https://economictimes.indiatimes.com/markets...,['Ahmedabad -based RBZ Jewellers gets IPO nod'],['The proceeds to the extent of ₹80.75 crore w...,"[""Mumbai: Ahmedabad -based RBZ Jewellers recei..."
307,506,https://www.chittorgarh.com/ipo/azad-engineeri...,Azad Engineering Limited IPO,"Dec 20, 2023",2023-12-22,"Dec 28, 2023",524,740.00,28,"BSE, NSE",...,7.32%,11,2023,azad engineering limited,Producer Manufacturing,Metal Fabrication,NaN,NaN,NaN,NaN
191,316,https://www.chittorgarh.com/ipo/innova-captab-...,Innova Captab Limited IPO,"Dec 21, 2023",2023-12-26,"Dec 29, 2023",448,570.00,33,"BSE, NSE",...,7.32%,11,2023,innova captab limited,Health Technology,Pharmaceuticals: Major,['https://economictimes.indiatimes.com/markets...,['Indifra IPO subscribed 1.26 times on Day 2. ...,['Indifra IPO is a fixed price issue of Rs 14....,"[""The initial public offering (IPO) of Indifra..."

In [ ]:
data_sort['Sector'].nunique()

19

In [ ]:
data_sort['Sector'].unique()

array(['Technology Services', 'Consumer Services', 'Process Industries',
       'Utilities', 'Consumer Non-Durables', 'Energy Minerals',
       'Producer Manufacturing', 'Distribution Services',
       'Industrial Services', 'Finance', 'Health Technology',
       'Consumer Durables', 'Transportation', 'Electronic Technology',
       'Non-Energy Minerals', 'Commercial Services', 'Retail Trade',
       'Health Services', 'Communications'], dtype=object)

In [ ]:
pd.isnull(data_sort['Sector']).value_counts()

Sector
False    418
Name: count, dtype: int64

In [ ]:
data_sort[pd.isnull(data_sort['Sector'])]

Empty DataFrame
Columns: [mapping_key, url, Issuer Company, Open Date, Close Date, Listing Date, Issue Price (Rs), Issue Size (Rs Cr.), Lot Size, Exchange, subscription_link, subscription_info, price_info, Date, QIB, NII, Retail, Total, EMP, bNII (bids above ₹10L), sNII (bids below ₹10L), RII, Other, NSE_symbol, BSE_Final_Issue_Price, NSE_Final_Issue_Price, BSE_Open, NSE_Open, BSE_Low, NSE_Low, BSE_High, NSE_High, BSE_Last_Trade, NSE_Last_Trade, Total_subscriptions, elasticity, lot_size_rows, full_text_content, Close Year, Close Year Previous, GDP per capita growth (annual %), GDP growth (annual %), GDP (current US$), Unemployment, total (% of total labor force) (modeled ILO estimate), Stocks traded, total value (% of GDP), Personal remittances, received (% of GDP), Net trade in goods and services (BoP, current US$), GNI per capita growth (annual %), Inflation, consumer prices (annual %), GNI (current US$), Foreign direct investment, net inflows (BoP, current US$), Foreign direct investment, net (BoP, current US$), 1 day before Close Day, 1 week before Close Day week number, 1 week before Close Day year number, 1 month before Close Day month number, 1 month before Close Day year number, Price_nifty50_daily, Open_nifty50_daily, High_nifty50_daily, Low_nifty50_daily, Volume_nifty50_daily, Chg%_nifty50_daily, Price_nifty50_weekly, Open_nifty50_weekly, High_nifty50_weekly, Low_nifty50_weekly, Volume_nifty50_weekly, Chg%_nifty50_weekly, Price_nifty50_monthly, Open_nifty50_monthly, High_nifty50_monthly, Low_nifty50_monthly, Volume_nifty50_monthly, Chg%_nifty50_monthly, Price_vix_daily, Open_vix_daily, High_vix_daily, Low_vix_daily, Chg%_vix_daily, day, Price_vix_weekly, Open_vix_weekly, High_vix_weekly, Low_vix_weekly, Chg%_vix_weekly, week, Price_vix_monthly, Open_vix_monthly, High_vix_monthly, Low_vix_monthly, Chg%_vix_monthly, month, year, Company Name, Sector, Industry, news_url, news_headine, news_synopsis, ...]
Index: []

[0 rows x 101 columns]

In [ ]:
data_sort['Industry'].nunique()

94

In [ ]:
data_sort['Issue Price (Rs)'].max()

2150

In [ ]:
data_sort['NSE_Open'].max()

'₹99.70'

In [ ]:
data_sort['NSE_High'].max()

'₹992.70'

In [ ]:
data_sort['NSE_Last_Trade'].max() # Close price

'₹996.95'

In [ ]:
data_sort['NSE_Open'] = data_sort['NSE_Open'].apply(lambda x : float(x.replace('₹', '').replace(',', '')))
data_sort['NSE_High'] = data_sort['NSE_High'].apply(lambda x : float(x.replace('₹', '').replace(',', '')))
data_sort['NSE_Last_Trade'] = data_sort['NSE_Last_Trade'].apply(lambda x : float(x.replace('₹', '').replace(',', ''))) # Close price

In [ ]:
data_sort['NSE_Open'].max()

2725.0

In [ ]:
data_sort['NSE_High'].max()

3129.0

In [ ]:
data_sort['NSE_Last_Trade'].max()

3117.15

In [ ]:
data_sort['Success_Open'] = data_sort.apply(lambda x : 1 if x['NSE_Open'] > x['Issue Price (Rs)'] else 0, axis = 1)
data_sort['Success_Close'] = data_sort.apply(lambda x : 1 if x['NSE_Last_Trade'] > x['Issue Price (Rs)'] else 0, axis = 1)
data_sort['Success_High'] = data_sort.apply(lambda x : 1 if x['NSE_High'] > x['Issue Price (Rs)'] else 0, axis = 1)

In [ ]:
data_sort_use = data_sort[['Close Date', 'Sector' ,'Success_Open', 'Success_Close', 'Success_High']].copy()
data_sort_use['quarter']  = pd.PeriodIndex(data_sort_use['Close Date'], freq='Q')
data_sort_use

,Close Date,Sector,Success_Open,Success_Close,Success_High,quarter
263,2009-02-09,Technology Services,0,1,1,2009Q1
362,2009-06-26,Consumer Services,1,1,1,2009Q2
306,2009-07-17,Technology Services,1,1,1,2009Q3
11,2009-07-23,Process Industries,0,0,1,2009Q3
222,2009-07-31,Utilities,1,1,1,2009Q3
...,...,...,...,...,...,...
96,2023-12-21,Producer Manufacturing,1,1,1,2023Q4
130,2023-12-21,Retail Trade,1,1,1,2023Q4
343,2023-12-21,Consumer Durables,0,1,1,2023Q4
307,2023-12-22,Producer Manufacturing,1,1,1,2023Q4
191,2023-12-26,Health Technology,1,1,1,2023Q4

In [ ]:
data_sort_use['month_year'] = data_sort_use['Close Date'].dt.to_period('M')

In [ ]:
data_sort['Success_Open'].value_counts()

Success_Open
1    289
0    129
Name: count, dtype: int64

In [ ]:
data_sort['Success_Close'].value_counts()

Success_Close
1    280
0    138
Name: count, dtype: int64

In [ ]:
data_sort['Success_High'].value_counts()

Success_High
1    346
0     72
Name: count, dtype: int64

In [ ]:
all_data  = pd.read_excel('main_data_with_indics_nifty50daily_weekly_monthly_vix_daily_weekly_monthly_ddreview.xlsx')
all_data.columns

Index(['mapping_key', 'url', 'Issuer Company', 'Open Date', 'Close Date',
       'Listing Date', 'Issue Price (Rs)', 'Issue Size (Rs Cr.)', 'Lot Size',
       'Exchange',
       ...
       'High_vix_monthly', 'Low_vix_monthly', 'Volume_vix_monthly',
       'Chg%_vix_monthly', 'month', 'year', 'Review Title', 'Recommendation',
       'review_url', 'review_text'],
      dtype='object', length=105)

In [ ]:
all_data['Close Date'] = pd.to_datetime(all_data['Close Date'])
all_data[['Close Date', 'year', 'month']]

    Close Date    year  month
0   2016-03-23  2016.0    2.0
1   2020-09-11  2020.0    8.0
2   2023-10-03  2023.0    9.0
3   2023-10-20  2023.0    9.0
4   2017-01-25  2016.0   12.0
..         ...     ...    ...
693 2011-04-21  2011.0    3.0
694 2007-03-01     NaN    NaN
695 2016-11-22  2016.0   10.0
696 2007-02-23     NaN    NaN
697 2011-01-06  2010.0   12.0

[698 rows x 3 columns]

In [ ]:
all_data['quarter']  = pd.PeriodIndex(all_data['Close Date'], freq='Q')

In [ ]:
all_data[all_data['quarter']=='2008Q4']

,mapping_key,url,Issuer Company,Open Date,Close Date,Listing Date,Issue Price (Rs),Issue Size (Rs Cr.),Lot Size,Exchange,...,Low_vix_monthly,Volume_vix_monthly,Chg%_vix_monthly,month,year,Review Title,Recommendation,review_url,review_text,quarter
537,537,https://www.chittorgarh.com/ipo/alkali_metals_...,Alkali Metals Limited IPO,"Oct 07, 2008",2008-10-15,NaN,103.00,26.27,65.0,"BSE, NSE",...,23.59,0.0,17.43%,9.0,2008.0,NaN,NaN,NaN,NaN,2008Q4

In [ ]:
all_data[all_data['quarter']=='2008Q4']['Issue Price (Rs)']

537    103.00
Name: Issue Price (Rs), dtype: object

In [ ]:
all_data[all_data['quarter']=='2008Q4']['NSE_Open']

537    ₹99.00
Name: NSE_Open, dtype: object

In [ ]:
all_data[all_data['quarter']=='2008Q4']['NSE_High']

537    ₹179.00
Name: NSE_High, dtype: object

In [ ]:
all_data[all_data['quarter']=='2008Q4']['NSE_Last_Trade']

537    ₹173.40
Name: NSE_Last_Trade, dtype: object

In [ ]:
sucess_ipo_quarterwise = data_sort_use.groupby('quarter', as_index = False)[['Success_Open', 'Success_Close', 'Success_High']].mean()
sucess_ipo_quarterwise

   quarter  Success_Open  Success_Close  Success_High
0   2009Q1      0.000000       1.000000      1.000000
1   2009Q2      1.000000       1.000000      1.000000
2   2009Q3      0.777778       0.555556      1.000000
3   2009Q4      0.888889       0.777778      1.000000
4   2010Q1      0.777778       0.555556      0.888889
5   2010Q2      0.500000       0.375000      0.875000
6   2010Q3      0.882353       0.705882      0.882353
7   2010Q4      0.846154       0.769231      1.000000
8   2011Q1      0.714286       0.571429      0.857143
9   2011Q2      0.500000       0.500000      0.700000
10  2011Q3      0.555556       0.444444      1.000000
11  2011Q4      0.800000       0.600000      1.000000
12  2012Q1      0.500000       0.500000      0.500000
13  2012Q2      0.500000       0.500000      0.500000
14  2012Q3      1.000000       0.000000      1.000000
15  2012Q4      0.750000       0.500000      0.750000
16  2013Q1      0.500000       0.000000      1.000000
17  2013Q2      1.000000       1.000000      1.000000
18  2014Q2      1.000000       1.000000      1.000000
19  2014Q3      1.000000       1.000000      1.000000
20  2014Q4      0.000000       0.000000      0.000000
21  2015Q1      0.333333       0.666667      0.666667
22  2015Q2      0.600000       0.400000      0.800000
23  2015Q3      0.285714       0.571429      0.571429
24  2015Q4      0.833333       0.833333      0.833333
25  2016Q1      0.500000       0.500000      0.666667
26  2016Q2      1.000000       1.000000      1.000000
27  2016Q3      0.700000       0.700000      0.700000
28  2016Q4      0.800000       1.000000      1.000000
29  2017Q1      0.800000       0.800000      0.800000
30  2017Q2      0.500000       0.600000      0.800000
31  2017Q3      0.727273       0.818182      1.000000
32  2017Q4      0.416667       0.583333      0.750000
33  2018Q1      0.500000       0.500000      0.642857
34  2018Q2      1.000000       1.000000      1.000000
35  2018Q3      0.200000       0.400000      0.600000
36  2018Q4      0.000000       0.000000      0.000000
37  2019Q1      0.500000       0.500000      0.500000
38  2019Q2      0.800000       1.000000      1.000000
39  2019Q3      0.333333       0.333333      0.666667
40  2019Q4      0.800000       0.800000      0.800000
41  2020Q1      0.000000       0.000000      0.000000
42  2020Q3      0.800000       0.800000      0.800000
43  2020Q4      0.750000       0.750000      0.875000
44  2021Q1      0.625000       0.625000      0.687500
45  2021Q2      0.833333       0.833333      0.833333
46  2021Q3      0.764706       0.705882      0.823529
47  2021Q4      0.695652       0.695652      0.869565
48  2022Q1      0.400000       0.600000      0.800000
49  2022Q2      0.727273       0.636364      0.727273
50  2022Q3      0.750000       0.750000      1.000000
51  2022Q4      0.647059       0.588235      0.705882
52  2023Q1      0.750000       0.750000      0.750000
53  2023Q2      0.833333       0.666667      0.833333
54  2023Q3      0.826087       0.826087      0.913043
55  2023Q4      0.791667       0.875000      0.875000

In [ ]:
sucess_ipo_quarterwise.to_excel('sucess_ipo_quarterwise.xlsx', index = False)

In [ ]:
data_sort_use.groupby(['quarter', 'Sector'], as_index = False)[['Success_Open', 'Success_Close', 'Success_High']].mean()

    quarter                  Sector  Success_Open  Success_Close  Success_High
0    2009Q1     Technology Services           0.0            1.0           1.0
1    2009Q2       Consumer Services           1.0            1.0           1.0
2    2009Q3   Consumer Non-Durables           1.0            0.0           1.0
3    2009Q3   Distribution Services           0.0            0.0           1.0
4    2009Q3         Energy Minerals           1.0            1.0           1.0
..      ...                     ...           ...            ...           ...
278  2023Q4     Industrial Services           0.0            0.0           0.0
279  2023Q4      Process Industries           1.0            1.0           1.0
280  2023Q4  Producer Manufacturing           1.0            1.0           1.0
281  2023Q4            Retail Trade           1.0            1.0           1.0
282  2023Q4     Technology Services           1.0            1.0           1.0

[283 rows x 5 columns]

In [ ]:
data_sort_use['Sector'].nunique()

19

In [ ]:
56 * 19 # 56 quarters, 19 sectors.. We are supposed to have 56*19 = 1064 entiries... but we have only 283 entries. Thus if we are using performance in the same sector last quarter, it will mostly be blanks

1064

In [ ]:
data_sort_use.groupby('month_year', as_index = False)[['Success_Open', 'Success_Close', 'Success_High']].mean()

    month_year  Success_Open  Success_Close  Success_High
0      2009-02      0.000000       1.000000      1.000000
1      2009-06      1.000000       1.000000      1.000000
2      2009-07      0.666667       0.666667      1.000000
3      2009-08      1.000000       1.000000      1.000000
4      2009-09      0.800000       0.400000      1.000000
..         ...           ...            ...           ...
124    2023-08      1.000000       1.000000      1.000000
125    2023-09      0.692308       0.769231      0.846154
126    2023-10      0.750000       0.750000      0.750000
127    2023-11      0.888889       1.000000      1.000000
128    2023-12      0.727273       0.818182      0.818182

[129 rows x 4 columns]

In [ ]:
(2023-2009+1) * 12 # Years considered 2009 to 2023 (both inclusive), theer are 12 months in a year

# So, ideally we will have 180 rowa, but we have 129 rows i.e. around 29% data is missing

# Thus, we will consider only by quarter

180

In [ ]:
129/180

0.7166666666666667

In [ ]:
data_sort

,mapping_key,url,Issuer Company,Open Date,Close Date,Listing Date,Issue Price (Rs),Issue Size (Rs Cr.),Lot Size,Exchange,...,Company Name,Sector,Industry,news_url,news_headine,news_synopsis,news_content,Success_Open,Success_Close,Success_High
263,433,https://www.chittorgarh.com/ipo/edserv_softsys...,Edserv Softsystems Limited IPO,"Feb 05, 2009",2009-02-09,"Mar 02, 2009",60,23.84,100,"BSE, NSE",...,edserv soft systems ltd.,Technology Services,Packaged Software,NaN,NaN,NaN,NaN,0,1,1
362,607,https://www.chittorgarh.com/ipo/mahindra_holid...,Mahindra Holidays and Resorts India Ltd IPO,"Jun 23, 2009",2009-06-26,"Jul 16, 2009",300,277.96,20,"BSE, NSE",...,mahindra holidays & resorts in,Consumer Services,Other Consumer Services,NaN,NaN,NaN,NaN,1,1,1
306,504,https://www.chittorgarh.com/ipo/excel_infoways...,Excel Infoways Limited IPO,"Jul 14, 2009",2009-07-17,"Aug 3, 2009",85,48.17,80,"BSE, NSE",...,excel infoway limited,Technology Services,Information Technology Services,NaN,NaN,NaN,NaN,1,1,1
11,15,https://www.chittorgarh.com/ipo/raj_oil_mills_...,Raj Oil Mills Limited IPO,"Jul 20, 2009",2009-07-23,"Aug 12, 2009",120,114.00,50,"BSE, NSE",...,raj oil mills ltd,Process Industries,Agricultural Commodities/Milling,NaN,NaN,NaN,NaN,0,0,1
222,369,https://www.chittorgarh.com/ipo/adani_power_ip...,Adani Power Limited IPO,"Jul 28, 2009",2009-07-31,"Aug 20, 2009",100,3016.52,65,"BSE, NSE",...,adani power ltd,Utilities,Electric Utilities,NaN,NaN,NaN,NaN,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,166,https://www.chittorgarh.com/ipo/happy-forgings...,Happy Forgings Limited IPO,"Dec 19, 2023",2023-12-21,"Dec 27, 2023",850,1008.59,17,"BSE, NSE",...,happy forgings limited,Producer Manufacturing,Metal Fabrication,NaN,NaN,NaN,NaN,1,1,1
130,214,https://www.chittorgarh.com/ipo/mufti-ipo/1595/,Credo Brands Marketing Limited IPO,"Dec 19, 2023",2023-12-21,"Dec 27, 2023",280,549.78,53,"BSE, NSE",...,credo brands marketing limited,Retail Trade,Apparel/Footwear Retail,NaN,NaN,NaN,NaN,1,1,1
343,568,https://www.chittorgarh.com/ipo/rbz-jewellers-...,RBZ Jewellers Limited IPO,"Dec 19, 2023",2023-12-21,"Dec 27, 2023",100,100.00,150,"BSE, NSE",...,rbz jewellers limited,Consumer Durables,Other Consumer Specialties,['https://economictimes.indiatimes.com/markets...,['Ahmedabad -based RBZ Jewellers gets IPO nod'],['The proceeds to the extent of ₹80.75 crore w...,"[""Mumbai: Ahmedabad -based RBZ Jewellers recei...",0,1,1
307,506,https://www.chittorgarh.com/ipo/azad-engineeri...,Azad Engineering Limited IPO,"Dec 20, 2023",2023-12-22,"Dec 28, 2023",524,740.00,28,"BSE, NSE",...,azad engineering limited,Producer Manufacturing,Metal Fabrication,NaN,NaN,NaN,NaN,1,1,1
191,316,https://www.chittorgarh.com/ipo/innova-captab-...,Innova Captab Limited IPO,"Dec 21, 2023",2023-12-26,"Dec 29, 2023",448,570.00,33,"BSE, NSE",...,innova captab limited,Health Technology,Pharmaceuticals: Major,['https://economictimes.indiatimes.com/markets...,['Indifra IPO subscribed 1.26 times on Day 2. ...,['Indifra IPO is a fixed price issue of Rs 14....,"[""The initial public offering (IPO) of Indifra...",1,1,1

In [ ]:
data_sort['previous_quater'] = pd.PeriodIndex(data_sort['Close Date'].apply(lambda x : x - pd.Timedelta(90, unit='D')), freq='Q')

In [ ]:
data_sort = data_sort.rename(columns = {'year' : 'previous_year', 'month' : 'previous_month', 'day' : 'previous_day', 'week' : 'previous_week'})
data_sort

,mapping_key,url,Issuer Company,Open Date,Close Date,Listing Date,Issue Price (Rs),Issue Size (Rs Cr.),Lot Size,Exchange,...,Sector,Industry,news_url,news_headine,news_synopsis,news_content,Success_Open,Success_Close,Success_High,previous_quater
263,433,https://www.chittorgarh.com/ipo/edserv_softsys...,Edserv Softsystems Limited IPO,"Feb 05, 2009",2009-02-09,"Mar 02, 2009",60,23.84,100,"BSE, NSE",...,Technology Services,Packaged Software,NaN,NaN,NaN,NaN,0,1,1,2008Q4
362,607,https://www.chittorgarh.com/ipo/mahindra_holid...,Mahindra Holidays and Resorts India Ltd IPO,"Jun 23, 2009",2009-06-26,"Jul 16, 2009",300,277.96,20,"BSE, NSE",...,Consumer Services,Other Consumer Services,NaN,NaN,NaN,NaN,1,1,1,2009Q1
306,504,https://www.chittorgarh.com/ipo/excel_infoways...,Excel Infoways Limited IPO,"Jul 14, 2009",2009-07-17,"Aug 3, 2009",85,48.17,80,"BSE, NSE",...,Technology Services,Information Technology Services,NaN,NaN,NaN,NaN,1,1,1,2009Q2
11,15,https://www.chittorgarh.com/ipo/raj_oil_mills_...,Raj Oil Mills Limited IPO,"Jul 20, 2009",2009-07-23,"Aug 12, 2009",120,114.00,50,"BSE, NSE",...,Process Industries,Agricultural Commodities/Milling,NaN,NaN,NaN,NaN,0,0,1,2009Q2
222,369,https://www.chittorgarh.com/ipo/adani_power_ip...,Adani Power Limited IPO,"Jul 28, 2009",2009-07-31,"Aug 20, 2009",100,3016.52,65,"BSE, NSE",...,Utilities,Electric Utilities,NaN,NaN,NaN,NaN,1,1,1,2009Q2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,166,https://www.chittorgarh.com/ipo/happy-forgings...,Happy Forgings Limited IPO,"Dec 19, 2023",2023-12-21,"Dec 27, 2023",850,1008.59,17,"BSE, NSE",...,Producer Manufacturing,Metal Fabrication,NaN,NaN,NaN,NaN,1,1,1,2023Q3
130,214,https://www.chittorgarh.com/ipo/mufti-ipo/1595/,Credo Brands Marketing Limited IPO,"Dec 19, 2023",2023-12-21,"Dec 27, 2023",280,549.78,53,"BSE, NSE",...,Retail Trade,Apparel/Footwear Retail,NaN,NaN,NaN,NaN,1,1,1,2023Q3
343,568,https://www.chittorgarh.com/ipo/rbz-jewellers-...,RBZ Jewellers Limited IPO,"Dec 19, 2023",2023-12-21,"Dec 27, 2023",100,100.00,150,"BSE, NSE",...,Consumer Durables,Other Consumer Specialties,['https://economictimes.indiatimes.com/markets...,['Ahmedabad -based RBZ Jewellers gets IPO nod'],['The proceeds to the extent of ₹80.75 crore w...,"[""Mumbai: Ahmedabad -based RBZ Jewellers recei...",0,1,1,2023Q3
307,506,https://www.chittorgarh.com/ipo/azad-engineeri...,Azad Engineering Limited IPO,"Dec 20, 2023",2023-12-22,"Dec 28, 2023",524,740.00,28,"BSE, NSE",...,Producer Manufacturing,Metal Fabrication,NaN,NaN,NaN,NaN,1,1,1,2023Q3
191,316,https://www.chittorgarh.com/ipo/innova-captab-...,Innova Captab Limited IPO,"Dec 21, 2023",2023-12-26,"Dec 29, 2023",448,570.00,33,"BSE, NSE",...,Health Technology,Pharmaceuticals: Major,['https://economictimes.indiatimes.com/markets...,['Indifra IPO subscribed 1.26 times on Day 2. ...,['Indifra IPO is a fixed price issue of Rs 14....,"[""The initial public offering (IPO) of Indifra...",1,1,1,2023Q3

In [ ]:
list(data_sort.columns)

['mapping_key',
 'url',
 'Issuer Company',
 'Open Date',
 'Close Date',
 'Listing Date',
 'Issue Price (Rs)',
 'Issue Size (Rs Cr.)',
 'Lot Size',
 'Exchange',
 'subscription_link',
 'subscription_info',
 'price_info',
 'Date',
 'QIB',
 'NII',
 'Retail',
 'Total',
 'EMP',
 'bNII (bids above ₹10L)',
 'sNII (bids below ₹10L)',
 'RII',
 'Other',
 'NSE_symbol',
 'BSE_Final_Issue_Price',
 'NSE_Final_Issue_Price',
 'BSE_Open',
 'NSE_Open',
 'BSE_Low',
 'NSE_Low',
 'BSE_High',
 'NSE_High',
 'BSE_Last_Trade',
 'NSE_Last_Trade',
 'Total_subscriptions',
 'elasticity',
 'lot_size_rows',
 'full_text_content',
 'Close Year',
 'Close Year Previous',
 'GDP per capita growth (annual %)',
 'GDP growth (annual %)',
 'GDP (current US$)',
 'Unemployment, total (% of total labor force) (modeled ILO estimate)',
 'Stocks traded, total value (% of GDP)',
 'Personal remittances, received (% of GDP)',
 'Net trade in goods and services (BoP, current US$)',
 'GNI per capita growth (annual %)',
 'Inflation, consumer prices (annual %)',
 'GNI (current US$)',
 'Foreign direct investment, net inflows (BoP, current US$)',
 'Foreign direct investment, net (BoP, current US$)',
 '1 day before Close Day',
 '1 week before Close Day week number',
 '1 week before Close Day year number',
 '1 month before Close Day month number',
 '1 month before Close Day year number',
 'Price_nifty50_daily',
 'Open_nifty50_daily',
 'High_nifty50_daily',
 'Low_nifty50_daily',
 'Volume_nifty50_daily',
 'Chg%_nifty50_daily',
 'Price_nifty50_weekly',
 'Open_nifty50_weekly',
 'High_nifty50_weekly',
 'Low_nifty50_weekly',
 'Volume_nifty50_weekly',
 'Chg%_nifty50_weekly',
 'Price_nifty50_monthly',
 'Open_nifty50_monthly',
 'High_nifty50_monthly',
 'Low_nifty50_monthly',
 'Volume_nifty50_monthly',
 'Chg%_nifty50_monthly',
 'Price_vix_daily',
 'Open_vix_daily',
 'High_vix_daily',
 'Low_vix_daily',
 'Chg%_vix_daily',
 'previous_day',
 'Price_vix_weekly',
 'Open_vix_weekly',
 'High_vix_weekly',
 'Low_vix_weekly',
 'Chg%_vix_weekly',
 'previous_week',
 'Price_vix_monthly',
 'Open_vix_monthly',
 'High_vix_monthly',
 'Low_vix_monthly',
 'Chg%_vix_monthly',
 'previous_month',
 'previous_year',
 'Company Name',
 'Sector',
 'Industry',
 'news_url',
 'news_headine',
 'news_synopsis',
 'news_content',
 'Success_Open',
 'Success_Close',
 'Success_High',
 'previous_quater']

In [ ]:
data_ipo_quarterwise_new = pd.read_excel('sucess_ipo_quarterwise.xlsx').rename(columns = {'quarter':'previous_quater', 'Success_Open' : 'previous_quarter_success_open', 'Success_Close' : 'previous_quarter_success_close', 'Success_High' : 'previous_quarter_success_high' })
data_ipo_quarterwise_new

,previous_quater,previous_quarter_success_open,previous_quarter_success_close,previous_quarter_success_high
0,2008Q4,0.000000,1.000000,1.000000
1,2009Q1,0.000000,1.000000,1.000000
2,2009Q2,1.000000,1.000000,1.000000
3,2009Q3,0.777778,0.555556,1.000000
4,2009Q4,0.888889,0.777778,1.000000
5,2010Q1,0.777778,0.555556,0.888889
6,2010Q2,0.500000,0.375000,0.875000
7,2010Q3,0.882353,0.705882,0.882353
8,2010Q4,0.846154,0.769231,1.000000
9,2011Q1,0.714286,0.571429,0.857143
10,2011Q2,0.500000,0.500000,0.700000
11,2011Q3,0.555556,0.444444,1.000000
12,2011Q4,0.800000,0.600000,1.000000
13,2012Q1,0.500000,0.500000,0.500000
14,2012Q2,0.500000,0.500000,0.500000
15,2012Q3,1.000000,0.000000,1.000000
16,2012Q4,0.750000,0.500000,0.750000
17,2013Q1,0.500000,0.000000,1.000000
18,2013Q2,1.000000,1.000000,1.000000
19,2014Q2,1.000000,1.000000,1.000000
20,2014Q3,1.000000,1.000000,1.000000
21,2014Q4,0.000000,0.000000,0.000000
22,2015Q1,0.333333,0.666667,0.666667
23,2015Q2,0.600000,0.400000,0.800000
24,2015Q3,0.285714,0.571429,0.571429
25,2015Q4,0.833333,0.833333,0.833333
26,2016Q1,0.500000,0.500000,0.666667
27,2016Q2,1.000000,1.000000,1.000000
28,2016Q3,0.700000,0.700000,0.700000
29,2016Q4,0.800000,1.000000,1.000000
30,2017Q1,0.800000,0.800000,0.800000
31,2017Q2,0.500000,0.600000,0.800000
32,2017Q3,0.727273,0.818182,1.000000
33,2017Q4,0.416667,0.583333,0.750000
34,2018Q1,0.500000,0.500000,0.642857
35,2018Q2,1.000000,1.000000,1.000000
36,2018Q3,0.200000,0.400000,0.600000
37,2018Q4,0.000000,0.000000,0.000000
38,2019Q1,0.500000,0.500000,0.500000
39,2019Q2,0.800000,1.000000,1.000000
40,2019Q3,0.333333,0.333333,0.666667
41,2019Q4,0.800000,0.800000,0.800000
42,2020Q1,0.000000,0.000000,0.000000
43,2020Q3,0.800000,0.800000,0.800000
44,2020Q4,0.750000,0.750000,0.875000
45,2021Q1,0.625000,0.625000,0.687500
46,2021Q2,0.833333,0.833333,0.833333
47,2021Q3,0.764706,0.705882,0.823529
48,2021Q4,0.695652,0.695652,0.869565
49,2022Q1,0.400000,0.600000,0.800000
50,2022Q2,0.727273,0.636364,0.727273
51,2022Q3,0.750000,0.750000,1.000000
52,2022Q4,0.647059,0.588235,0.705882
53,2023Q1,0.750000,0.750000,0.750000
54,2023Q2,0.833333,0.666667,0.833333
55,2023Q3,0.826087,0.826087,0.913043
56,2023Q4,0.791667,0.875000,0.875000

In [ ]:
data_sort['previous_quater'] = data_sort['previous_quater'].apply(lambda x : str(x))

In [ ]:
final_df = data_sort.merge(data_ipo_quarterwise_new, on = 'previous_quater', how = 'left')
final_df = final_df.rename(columns = {'previous_quater' : 'previous_quarter'})
final_df

,mapping_key,url,Issuer Company,Open Date,Close Date,Listing Date,Issue Price (Rs),Issue Size (Rs Cr.),Lot Size,Exchange,...,news_headine,news_synopsis,news_content,Success_Open,Success_Close,Success_High,previous_quarter,previous_quarter_success_open,previous_quarter_success_close,previous_quarter_success_high
0,433,https://www.chittorgarh.com/ipo/edserv_softsys...,Edserv Softsystems Limited IPO,"Feb 05, 2009",2009-02-09,"Mar 02, 2009",60,23.84,100,"BSE, NSE",...,NaN,NaN,NaN,0,1,1,2008Q4,0.000000,1.000000,1.000000
1,607,https://www.chittorgarh.com/ipo/mahindra_holid...,Mahindra Holidays and Resorts India Ltd IPO,"Jun 23, 2009",2009-06-26,"Jul 16, 2009",300,277.96,20,"BSE, NSE",...,NaN,NaN,NaN,1,1,1,2009Q1,0.000000,1.000000,1.000000
2,504,https://www.chittorgarh.com/ipo/excel_infoways...,Excel Infoways Limited IPO,"Jul 14, 2009",2009-07-17,"Aug 3, 2009",85,48.17,80,"BSE, NSE",...,NaN,NaN,NaN,1,1,1,2009Q2,1.000000,1.000000,1.000000
3,15,https://www.chittorgarh.com/ipo/raj_oil_mills_...,Raj Oil Mills Limited IPO,"Jul 20, 2009",2009-07-23,"Aug 12, 2009",120,114.00,50,"BSE, NSE",...,NaN,NaN,NaN,0,0,1,2009Q2,1.000000,1.000000,1.000000
4,369,https://www.chittorgarh.com/ipo/adani_power_ip...,Adani Power Limited IPO,"Jul 28, 2009",2009-07-31,"Aug 20, 2009",100,3016.52,65,"BSE, NSE",...,NaN,NaN,NaN,1,1,1,2009Q2,1.000000,1.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,166,https://www.chittorgarh.com/ipo/happy-forgings...,Happy Forgings Limited IPO,"Dec 19, 2023",2023-12-21,"Dec 27, 2023",850,1008.59,17,"BSE, NSE",...,NaN,NaN,NaN,1,1,1,2023Q3,0.826087,0.826087,0.913043
414,214,https://www.chittorgarh.com/ipo/mufti-ipo/1595/,Credo Brands Marketing Limited IPO,"Dec 19, 2023",2023-12-21,"Dec 27, 2023",280,549.78,53,"BSE, NSE",...,NaN,NaN,NaN,1,1,1,2023Q3,0.826087,0.826087,0.913043
415,568,https://www.chittorgarh.com/ipo/rbz-jewellers-...,RBZ Jewellers Limited IPO,"Dec 19, 2023",2023-12-21,"Dec 27, 2023",100,100.00,150,"BSE, NSE",...,['Ahmedabad -based RBZ Jewellers gets IPO nod'],['The proceeds to the extent of ₹80.75 crore w...,"[""Mumbai: Ahmedabad -based RBZ Jewellers recei...",0,1,1,2023Q3,0.826087,0.826087,0.913043
416,506,https://www.chittorgarh.com/ipo/azad-engineeri...,Azad Engineering Limited IPO,"Dec 20, 2023",2023-12-22,"Dec 28, 2023",524,740.00,28,"BSE, NSE",...,NaN,NaN,NaN,1,1,1,2023Q3,0.826087,0.826087,0.913043
417,316,https://www.chittorgarh.com/ipo/innova-captab-...,Innova Captab Limited IPO,"Dec 21, 2023",2023-12-26,"Dec 29, 2023",448,570.00,33,"BSE, NSE",...,['Indifra IPO subscribed 1.26 times on Day 2. ...,['Indifra IPO is a fixed price issue of Rs 14....,"[""The initial public offering (IPO) of Indifra...",1,1,1,2023Q3,0.826087,0.826087,0.913043

In [ ]:
final_df.to_excel('main_data_with_indics_nifty50daily_weekly_monthly_vix_daily_weekly_monthly_FITERED_CLEANED_industry_news_prevperformance_v6.xlsx', index = False)

In [ ]:
def dynamic_quater(close_date_now, days=90):
  final_df_use = final_df[(final_df['Close Date']<close_date_now) & (final_df['Close Date']>=close_date_now-pd.Timedelta(days, unit='D'))]
  li = final_df_use[['Success_Open', 'Success_Close', 'Success_High']].mean()
  return [li[0], li[1], li[2]]

In [ ]:
import numpy as np

In [ ]:
li_of_li = [[0,1,1]] # 2008 data added manually
for close_date in final_df["Close Date"][1:]: # 2008 data added manually so starting from 1st index (and not 0th index)
  li = dynamic_quater(close_date)
  if str(li[0]) == 'nan': # If there were no ipo inn previous quarter, we are considering the penultimate quarter
    li_of_li.append(li_of_li[-1])
  else:
    li_of_li.append(li)

li_of_li

[[0, 1, 1],
 [0, 1, 1],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [0.6666666666666666, 0.6666666666666666, 1.0],
 [0.75, 0.75, 1.0],
 [0.8, 0.8, 1.0],
 [0.8333333333333334, 0.8333333333333334, 1.0],
 [0.8571428571428571, 0.7142857142857143, 1.0],
 [0.875, 0.75, 1.0],
 [0.8888888888888888, 0.6666666666666666, 1.0],
 [0.7777777777777778, 0.5555555555555556, 1.0],
 [0.8, 0.6, 1.0],
 [0.875, 0.5, 1.0],
 [0.7777777777777778, 0.4444444444444444, 1.0],
 [0.7777777777777778, 0.4444444444444444, 1.0],
 [0.7777777777777778, 0.4444444444444444, 1.0],
 [0.7777777777777778, 0.5555555555555556, 1.0],
 [0.7777777777777778, 0.5555555555555556, 1.0],
 [0.8, 0.6, 1.0],
 [0.875, 0.75, 1.0],
 [0.875, 0.875, 1.0],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [0.9090909090909091, 0.8181818181818182, 1.0],
 [0.9090909090909091, 0.8181818181818182, 1.0],
 [0.8333333333333334, 0.75, 0.9166666666666666],
 [0.8461538461538461, 0.6923076923076923, 0.9230769230769231],
 [0.8461538461538461, 0.6923076923076923, 0.9230769230769231],
 [0.8571428571428571, 0.6428571428571429, 0.9285714285714286],
 [0.8666666666666667, 0.6666666666666666, 0.9333333333333333],
 [0.875, 0.6875, 0.9375],
 [0.8571428571428571, 0.6428571428571429, 0.9285714285714286],
 [0.8571428571428571, 0.6428571428571429, 0.9285714285714286],
 [0.8666666666666667, 0.6, 0.9333333333333333],
 [0.875, 0.625, 0.9375],
 [0.8235294117647058, 0.5882352941176471, 0.8823529411764706],
 [0.75, 0.5, 0.875],
 [0.7647058823529411, 0.5294117647058824, 0.8823529411764706],
 [0.7222222222222222, 0.5, 0.8888888888888888],
 [0.6842105263157895, 0.47368421052631576, 0.8947368421052632],
 [0.7058823529411765, 0.5294117647058824, 0.8823529411764706],
 [0.75, 0.5, 0.9375],
 [0.4444444444444444, 0.3333333333333333, 0.7777777777777778],
 [0.42857142857142855, 0.2857142857142857, 0.8571428571428571],
 [0.5, 0.375, 0.875],
 [0.5555555555555556, 0.4444444444444444, 0.8888888888888888],
 [0.6, 0.6, 0.8],
 [0.8, 0.8, 1.0],
 [0.8333333333333334, 0.8333333333333334, 1.0],
 [0.8571428571428571, 0.8571428571428571, 1.0],
 [0.875, 0.875, 1.0],
 [1.0, 0.875, 1.0],
 [1.0, 0.875, 1.0],
 [1.0, 0.875, 1.0],
 [1.0, 0.8181818181818182, 1.0],
 [1.0, 0.75, 1.0],
 [1.0, 0.75, 1.0],
 [0.9230769230769231, 0.6923076923076923, 0.9230769230769231],
 [0.9230769230769231, 0.6923076923076923, 0.9230769230769231],
 [0.8666666666666667, 0.6666666666666666, 0.8666666666666667],
 [0.8666666666666667, 0.6666666666666666, 0.8666666666666667],
 [0.875, 0.6875, 0.875],
 [0.8823529411764706, 0.7058823529411765, 0.8823529411764706],
 [0.8235294117647058, 0.6470588235294118, 0.8823529411764706],
 [0.8333333333333334, 0.6666666666666666, 0.8888888888888888],
 [0.8421052631578947, 0.6842105263157895, 0.8947368421052632],
 [0.85, 0.7, 0.9],
 [0.8571428571428571, 0.7142857142857143, 0.9047619047619048],
 [0.8571428571428571, 0.7142857142857143, 0.9047619047619048],
 [0.85, 0.7, 0.9],
 [0.8, 0.65, 0.9],
 [0.8095238095238095, 0.6666666666666666, 0.9047619047619048],
 [0.8095238095238095, 0.6666666666666666, 0.9047619047619048],
 [0.8181818181818182, 0.6818181818181818, 0.9090909090909091],
 [0.9090909090909091, 0.8181818181818182, 1.0],
 [0.8571428571428571, 0.7142857142857143, 1.0],
 [0.8333333333333334, 0.6666666666666666, 1.0],
 [0.8333333333333334, 0.6666666666666666, 1.0],
 [0.8, 0.8, 1.0],
 [0.8, 0.8, 1.0],
 [0.6666666666666666, 0.6666666666666666, 0.8333333333333334],
 [0.6666666666666666, 0.5, 0.8333333333333334],
 [0.7142857142857143, 0.5714285714285714, 0.8571428571428571],
 [0.8571428571428571, 0.5714285714285714, 0.8571428571428571],
 [0.75, 0.5, 0.75],
 [0.75, 0.5, 0.75],
 [0.6, 0.4, 0.7],
 [0.5454545454545454, 0.36363636363636365, 0.6363636363636364],
 [0.5833333333333334, 0.4166666666666667, 0.6666666666666666],
 [0.45454545454545453, 0.36363636363636365, 0.6363636363636364],
 [0.5, 0.4, 0.7],
 [0.5, 0.5, 0.7],
 [0.4, 0.4, 0.7],
 [0.42857142857142855, 0.7142857142857143, 0.8571428571428571],
 [0.6, 0.6, 1.0],
 [0.5, 0.5, 1.0],
 [0.42857142857142855, 0.42857142857142855, 1.0],
 [0.42857142857142855, 0.42857142857142855, 1.0],
 [0.5, 0.375, 1.0],
 [0.5555555555555556, 0.4444444444444444, 1.0],
 [0.5555555555555556, 0.4444444444444444, 1.0],
 [0.5555555555555556, 0.4444444444444444, 1.0],
 [0.5454545454545454, 0.45454545454545453, 1.0],
 [0.5454545454545454, 0.45454545454545453, 1.0],
 [0.5454545454545454, 0.45454545454545453, 1.0],
 [0.5454545454545454, 0.45454545454545453, 1.0],
 [0.0, 0.0, 0.0],
 [0.5, 0.5, 0.5],
 [0.3333333333333333, 0.3333333333333333, 0.3333333333333333],
 [0.5, 0.5, 0.5],
 [0.5, 0.5, 0.5],
 [1.0, 0.0, 1.0],
 [1.0, 0.5, 1.0],
 [1.0, 0.6666666666666666, 1.0],
 [0.75, 0.5, 0.75],
 [1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0],
 [0.0, 0.0, 1.0],
 [0.0, 0.0, 1.0],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0],
 [0.0, 0.5, 0.5],
 [0.3333333333333333, 0.6666666666666666, 0.6666666666666666],
 [0.5, 0.75, 0.75],
 [0.6, 0.6, 0.8],
 [0.5, 0.5, 0.6666666666666666],
 [0.75, 0.25, 0.75],
 [0.3333333333333333, 0.3333333333333333, 0.6666666666666666],
 [0.5, 1.0, 1.0],
 [0.3333333333333333, 0.6666666666666666, 0.6666666666666666],
 [0.25, 0.75, 0.75],
 [0.25, 0.75, 0.75],
 [0.16666666666666666, 0.5, 0.5],
 [0.2857142857142857, 0.5714285714285714, 0.5714285714285714],
 [0.2857142857142857, 0.5714285714285714, 0.5714285714285714],
 [0.14285714285714285, 0.42857142857142855, 0.42857142857142855],
 [0.25, 0.5, 0.5],
 [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
 [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
 [0.8, 0.8, 0.8],
 [1.0, 1.0, 1.0],
 [0.75, 0.75, 0.75],
 [0.8, 0.8, 0.8],
 [0.5, 0.5, 0.75],
 [0.25, 0.25, 0.5],
 [0.4, 0.4, 0.6],
 [0.5, 0.5, 0.6666666666666666],
 [0.6666666666666666, 0.6666666666666666, 0.8333333333333334],
 [0.7142857142857143, 0.7142857142857143, 0.8571428571428571],
 [0.8333333333333334, 0.8333333333333334, 0.8333333333333334],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [0.8333333333333334, 0.8333333333333334, 0.8333333333333334],
 [0.8, 0.8, 0.8],
 [0.8333333333333334, 0.8333333333333334, 0.8333333333333334],
 [0.8333333333333334, 0.8333333333333334, 0.8333333333333334],
 [0.8571428571428571, 0.8571428571428571, 0.8571428571428571],
 [0.875, 0.875, 0.875],
 [0.8888888888888888, 0.8888888888888888, 0.8888888888888888],
 [0.7777777777777778, 0.7777777777777778, 0.7777777777777778],
 [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
 [0.75, 0.75, 0.75],
 [0.7777777777777778, 0.7777777777777778, 0.7777777777777778],
 [0.5714285714285714, 0.7142857142857143, 0.7142857142857143],
 [0.625, 0.75, 0.75],
 [0.75, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [0.75, 0.75, 0.75],
 [0.75, 0.75, 0.75],
 [0.8, 0.8, 0.8],
 [0.6666666666666666, 0.6666666666666666, 0.8333333333333334],
 [0.7142857142857143, 0.7142857142857143, 0.8571428571428571],
 [0.7142857142857143, 0.7142857142857143, 0.8571428571428571],
 [0.42857142857142855, 0.42857142857142855, 0.5714285714285714],
 [0.375, 0.5, 0.625],
 [0.5, 0.5, 0.75],
 [0.5, 0.5, 0.75],
 [0.4444444444444444, 0.5555555555555556, 0.7777777777777778],
 [0.5, 0.6, 0.8],
 [0.5, 0.6, 0.8],
 [0.5454545454545454, 0.5454545454545454, 0.8181818181818182],
 [0.75, 0.75, 1.0],
 [0.7777777777777778, 0.7777777777777778, 1.0],
 [0.7777777777777778, 0.7777777777777778, 1.0],
 [0.7272727272727273, 0.8181818181818182, 1.0],
 [0.7272727272727273, 0.7272727272727273, 1.0],
 [0.7272727272727273, 0.8181818181818182, 1.0],
 [0.7, 0.8, 1.0],
 [0.7272727272727273, 0.8181818181818182, 1.0],
 [0.7272727272727273, 0.8181818181818182, 1.0],
 [0.75, 0.8333333333333334, 1.0],
 [0.7692307692307693, 0.8461538461538461, 1.0],
 [0.7142857142857143, 0.7857142857142857, 1.0],
 [0.6428571428571429, 0.7142857142857143, 0.9285714285714286],
 [0.6153846153846154, 0.7692307692307693, 0.9230769230769231],
 [0.5714285714285714, 0.7857142857142857, 0.9285714285714286],
 [0.5333333333333333, 0.7333333333333333, 0.8666666666666667],
 [0.5, 0.6875, 0.8125],
 [0.5, 0.6875, 0.8125],
 [0.4666666666666667, 0.6, 0.8],
 [0.46153846153846156, 0.6153846153846154, 0.7692307692307693],
 [0.375, 0.625, 0.75],
 [0.4444444444444444, 0.6666666666666666, 0.7777777777777778],
 [0.5, 0.7, 0.8],
 [0.5, 0.7, 0.8],
 [0.7142857142857143, 0.8571428571428571, 1.0],
 [0.625, 0.75, 0.875],
 [0.7142857142857143, 0.7142857142857143, 0.8571428571428571],
 [0.625, 0.625, 0.75],
 [0.6666666666666666, 0.6666666666666666, 0.7777777777777778],
 [0.5555555555555556, 0.5555555555555556, 0.6666666666666666],
 [0.5555555555555556, 0.5555555555555556, 0.6666666666666666],
 [0.5454545454545454, 0.45454545454545453, 0.6363636363636364],
 [0.5, 0.5, 0.6666666666666666],
 [0.46153846153846156, 0.46153846153846156, 0.6153846153846154],
 [0.3, 0.3, 0.5],
 [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
 [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [0.8, 0.8, 1.0],
 [0.8, 0.8, 1.0],
 [0.6666666666666666, 0.8333333333333334, 1.0],
 [0.25, 0.5, 0.75],
 [0.2, 0.4, 0.6],
 [0.2, 0.4, 0.6],
 [1.0, 1.0, 1.0],
 [0.5, 0.5, 0.5],
 [0.3333333333333333, 0.6666666666666666, 0.6666666666666666],
 [0.5, 0.75, 0.75],
 [0.6, 0.8, 0.8],
 [0.75, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [0.6666666666666666, 0.6666666666666666, 1.0],
 [0.3333333333333333, 0.3333333333333333, 0.6666666666666666],
 [0.5, 0.5, 0.75],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [0.8, 0.8, 0.8],
 [0.8, 0.8, 0.8],
 [0.7142857142857143, 0.7142857142857143, 0.7142857142857143],
 [0.7142857142857143, 0.7142857142857143, 0.7142857142857143],
 [0.625, 0.625, 0.75],
 [0.6666666666666666, 0.6666666666666666, 0.7777777777777778],
 [0.625, 0.625, 0.75],
 [0.625, 0.625, 0.75],
 [0.8, 0.8, 1.0],
 [0.8, 0.8, 0.8],
 [0.8333333333333334, 0.8333333333333334, 0.8333333333333334],
 [0.8571428571428571, 0.8571428571428571, 0.8571428571428571],
 [0.8571428571428571, 0.8571428571428571, 0.8571428571428571],
 [0.875, 0.875, 0.875],
 [0.8888888888888888, 0.8888888888888888, 0.8888888888888888],
 [0.8888888888888888, 0.7777777777777778, 0.8888888888888888],
 [0.9, 0.8, 0.9],
 [0.9090909090909091, 0.8181818181818182, 0.9090909090909091],
 [0.8333333333333334, 0.75, 0.8333333333333334],
 [0.8333333333333334, 0.75, 0.8333333333333334],
 [0.7692307692307693, 0.6923076923076923, 0.7692307692307693],
 [0.7142857142857143, 0.6428571428571429, 0.7142857142857143],
 [0.7142857142857143, 0.6428571428571429, 0.7142857142857143],
 [0.6666666666666666, 0.6, 0.6666666666666666],
 [0.625, 0.625, 0.6875],
 [0.2, 0.4, 0.4],
 [0.2, 0.4, 0.4],
 [0.5, 0.75, 0.75],
 [0.5, 0.75, 0.75],
 [0.8, 0.8, 0.8],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [0.9285714285714286, 0.9285714285714286, 0.9285714285714286],
 [0.9285714285714286, 0.9285714285714286, 0.9285714285714286],
 [0.8125, 0.8125, 0.8125],
 [0.8125, 0.8125, 0.8125],
 [0.7777777777777778, 0.7222222222222222, 0.8333333333333334],
 [0.7777777777777778, 0.7222222222222222, 0.8333333333333334],
 [0.7777777777777778, 0.7222222222222222, 0.8333333333333334],
 [0.7647058823529411, 0.7058823529411765, 0.8235294117647058],
 [0.7647058823529411, 0.7058823529411765, 0.8235294117647058],
 [0.6923076923076923, 0.5384615384615384, 0.7692307692307693],
 [0.7142857142857143, 0.5714285714285714, 0.7857142857142857],
 [0.6666666666666666, 0.5333333333333333, 0.8],
 [0.6666666666666666, 0.5333333333333333, 0.8],
 [0.6666666666666666, 0.5333333333333333, 0.8],
 [0.75, 0.5833333333333334, 1.0],
 [0.7272727272727273, 0.6363636363636364, 0.9090909090909091],
 [0.75, 0.6666666666666666, 0.9166666666666666],
 [0.7692307692307693, 0.6923076923076923, 0.9230769230769231],
 [0.7857142857142857, 0.7142857142857143, 0.9285714285714286],
 [0.8, 0.7333333333333333, 0.9333333333333333],
 [0.7142857142857143, 0.7142857142857143, 0.9285714285714286],
 [0.7333333333333333, 0.7333333333333333, 0.9333333333333333],
 [0.75, 0.75, 0.9375],
 [0.7058823529411765, 0.7058823529411765, 0.8823529411764706],
 [0.6666666666666666, 0.6666666666666666, 0.8333333333333334],
 [0.6842105263157895, 0.6842105263157895, 0.8421052631578947],
 [0.65, 0.65, 0.85],
 [0.65, 0.65, 0.85],
 [0.6666666666666666, 0.6666666666666666, 0.8571428571428571],
 [0.6818181818181818, 0.6818181818181818, 0.8636363636363636],
 [0.6818181818181818, 0.6818181818181818, 0.8636363636363636],
 [0.6818181818181818, 0.7272727272727273, 0.8636363636363636],
 [0.6363636363636364, 0.6818181818181818, 0.8636363636363636],
 [0.631578947368421, 0.7368421052631579, 0.8421052631578947],
 [0.3333333333333333, 0.6666666666666666, 1.0],
 [0.5, 0.75, 1.0],
 [0.4, 0.6, 0.8],
 [0.6, 0.8, 0.8],
 [0.6666666666666666, 0.8333333333333334, 0.8333333333333334],
 [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
 [0.5, 0.5, 0.5],
 [0.5714285714285714, 0.42857142857142855, 0.5714285714285714],
 [0.5714285714285714, 0.42857142857142855, 0.5714285714285714],
 [0.6666666666666666, 0.5555555555555556, 0.6666666666666666],
 [0.7, 0.6, 0.7],
 [0.6363636363636364, 0.5454545454545454, 0.6363636363636364],
 [0.6666666666666666, 0.5833333333333334, 0.6666666666666666],
 [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [0.6666666666666666, 0.6666666666666666, 1.0],
 [0.75, 0.75, 1.0],
 [0.8, 0.8, 1.0],
 [0.8333333333333334, 0.8333333333333334, 1.0],
 [0.7142857142857143, 0.7142857142857143, 0.8571428571428571],
 [0.7142857142857143, 0.7142857142857143, 0.8571428571428571],
 [0.7777777777777778, 0.7777777777777778, 0.8888888888888888],
 [0.7777777777777778, 0.7777777777777778, 0.8888888888888888],
 [0.7272727272727273, 0.8181818181818182, 0.9090909090909091],
 [0.75, 0.8333333333333334, 0.9166666666666666],
 [0.6923076923076923, 0.7692307692307693, 0.8461538461538461],
 [0.6666666666666666, 0.75, 0.8333333333333334],
 [0.6923076923076923, 0.7692307692307693, 0.8461538461538461],
 [0.6923076923076923, 0.7692307692307693, 0.7692307692307693],
 [0.6923076923076923, 0.7692307692307693, 0.7692307692307693],
 [0.6428571428571429, 0.6428571428571429, 0.7142857142857143],
 [0.6666666666666666, 0.6, 0.7333333333333333],
 [0.625, 0.5625, 0.6875],
 [0.6470588235294118, 0.5882352941176471, 0.7058823529411765],
 [0.6666666666666666, 0.3333333333333333, 0.6666666666666666],
 [0.7142857142857143, 0.42857142857142855, 0.7142857142857143],
 [1.0, 1.0, 1.0],
 [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
 [0.5, 0.5, 0.5],
 [0.5, 0.25, 0.5],
 [0.6666666666666666, 0.3333333333333333, 0.6666666666666666],
 [0.75, 0.5, 0.75],
 [0.75, 0.5, 0.75],
 [1.0, 0.8, 1.0],
 [1.0, 0.8333333333333334, 1.0],
 [1.0, 0.8571428571428571, 1.0],
 [1.0, 1.0, 1.0],
 [1.0, 0.875, 1.0],
 [1.0, 0.8888888888888888, 1.0],
 [1.0, 0.9, 1.0],
 [1.0, 0.9090909090909091, 1.0],
 [1.0, 0.9166666666666666, 1.0],
 [1.0, 0.9230769230769231, 1.0],
 [1.0, 0.9285714285714286, 1.0],
 [1.0, 0.9333333333333333, 1.0],
 [1.0, 0.9333333333333333, 1.0],
 [1.0, 0.9375, 1.0],
 [1.0, 0.9411764705882353, 1.0],
 [1.0, 0.9444444444444444, 1.0],
 [1.0, 0.9444444444444444, 1.0],
 [0.95, 0.9, 1.0],
 [0.9, 0.85, 0.95],
 [0.9, 0.85, 0.95],
 [0.9090909090909091, 0.8636363636363636, 0.9545454545454546],
 [0.8695652173913043, 0.8695652173913043, 0.9565217391304348],
 [0.8695652173913043, 0.8695652173913043, 0.9565217391304348],
 [0.8260869565217391, 0.8260869565217391, 0.9130434782608695],
 [0.8260869565217391, 0.8260869565217391, 0.9130434782608695],
 [0.8181818181818182, 0.8181818181818182, 0.9090909090909091],
 [0.7727272727272727, 0.8181818181818182, 0.8636363636363636],
 [0.782608695652174, 0.8260869565217391, 0.8695652173913043],
 [0.7916666666666666, 0.8333333333333334, 0.875],
 [0.782608695652174, 0.8260869565217391, 0.8695652173913043],
 [0.7916666666666666, 0.8333333333333334, 0.875],
 [0.7727272727272727, 0.8181818181818182, 0.8636363636363636],
 [0.782608695652174, 0.8260869565217391, 0.8695652173913043],
 [0.782608695652174, 0.8260869565217391, 0.8695652173913043],
 [0.782608695652174, 0.8260869565217391, 0.8695652173913043],
 [0.782608695652174, 0.8260869565217391, 0.8695652173913043],
 [0.7142857142857143, 0.8095238095238095, 0.8571428571428571],
 [0.7142857142857143, 0.8095238095238095, 0.8571428571428571],
 [0.7619047619047619, 0.8571428571428571, 0.8571428571428571],
 [0.8095238095238095, 0.9047619047619048, 0.9047619047619048],
 [0.8095238095238095, 0.9047619047619048, 0.9047619047619048],
 [0.8095238095238095, 0.9047619047619048, 0.9047619047619048],
 [0.75, 0.8333333333333334, 0.8333333333333334],
 [0.75, 0.8333333333333334, 0.8333333333333334],
 [0.75, 0.8333333333333334, 0.8333333333333334],
 [0.72, 0.84, 0.84],
 [0.76, 0.84, 0.84]]

In [ ]:
len(li_of_li)

418

In [ ]:
final_df['dynamic_last_90Day_success_open'] = [i[0] for i in li_of_li]
final_df['dynamic_last_90Day_success_close'] = [i[1] for i in li_of_li]
final_df['dynamic_last_90Day_success_high'] = [i[2] for i in li_of_li]

In [ ]:
final_df

,mapping_key,url,Issuer Company,Open Date,Close Date,Listing Date,Issue Price (Rs),Issue Size (Rs Cr.),Lot Size,Exchange,...,Success_Open,Success_Close,Success_High,previous_quarter,previous_quarter_success_open,previous_quarter_success_close,previous_quarter_success_high,dynamic_last_90Day_success_open,dynamic_last_90Day_success_close,dynamic_last_90Day_success_high
0,433,https://www.chittorgarh.com/ipo/edserv_softsys...,Edserv Softsystems Limited IPO,"Feb 05, 2009",2009-02-09,"Mar 02, 2009",60,23.84,100,"BSE, NSE",...,0,1,1,2008Q4,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000
1,607,https://www.chittorgarh.com/ipo/mahindra_holid...,Mahindra Holidays and Resorts India Ltd IPO,"Jun 23, 2009",2009-06-26,"Jul 16, 2009",300,277.96,20,"BSE, NSE",...,1,1,1,2009Q1,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000
2,504,https://www.chittorgarh.com/ipo/excel_infoways...,Excel Infoways Limited IPO,"Jul 14, 2009",2009-07-17,"Aug 3, 2009",85,48.17,80,"BSE, NSE",...,1,1,1,2009Q2,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
3,15,https://www.chittorgarh.com/ipo/raj_oil_mills_...,Raj Oil Mills Limited IPO,"Jul 20, 2009",2009-07-23,"Aug 12, 2009",120,114.00,50,"BSE, NSE",...,0,0,1,2009Q2,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
4,369,https://www.chittorgarh.com/ipo/adani_power_ip...,Adani Power Limited IPO,"Jul 28, 2009",2009-07-31,"Aug 20, 2009",100,3016.52,65,"BSE, NSE",...,1,1,1,2009Q2,1.000000,1.000000,1.000000,0.666667,0.666667,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,166,https://www.chittorgarh.com/ipo/happy-forgings...,Happy Forgings Limited IPO,"Dec 19, 2023",2023-12-21,"Dec 27, 2023",850,1008.59,17,"BSE, NSE",...,1,1,1,2023Q3,0.826087,0.826087,0.913043,0.750000,0.833333,0.833333
414,214,https://www.chittorgarh.com/ipo/mufti-ipo/1595/,Credo Brands Marketing Limited IPO,"Dec 19, 2023",2023-12-21,"Dec 27, 2023",280,549.78,53,"BSE, NSE",...,1,1,1,2023Q3,0.826087,0.826087,0.913043,0.750000,0.833333,0.833333
415,568,https://www.chittorgarh.com/ipo/rbz-jewellers-...,RBZ Jewellers Limited IPO,"Dec 19, 2023",2023-12-21,"Dec 27, 2023",100,100.00,150,"BSE, NSE",...,0,1,1,2023Q3,0.826087,0.826087,0.913043,0.750000,0.833333,0.833333
416,506,https://www.chittorgarh.com/ipo/azad-engineeri...,Azad Engineering Limited IPO,"Dec 20, 2023",2023-12-22,"Dec 28, 2023",524,740.00,28,"BSE, NSE",...,1,1,1,2023Q3,0.826087,0.826087,0.913043,0.720000,0.840000,0.840000
417,316,https://www.chittorgarh.com/ipo/innova-captab-...,Innova Captab Limited IPO,"Dec 21, 2023",2023-12-26,"Dec 29, 2023",448,570.00,33,"BSE, NSE",...,1,1,1,2023Q3,0.826087,0.826087,0.913043,0.760000,0.840000,0.840000

In [ ]:
final_df.to_excel('main_data_with_indics_nifty50daily_weekly_monthly_vix_daily_weekly_monthly_FITERED_CLEANED_industry_news_prevperformance_dynamic_v7.xlsx', index = False)